[tool.black]
line-length = 100
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 100

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
strict = true
ignore_missing_imports = true

[tool.pytest.ini_options]
addopts = "-ra -q"
pythonpath = ["."]
